from treelib import Tree

tree = Tree()
tree.create_node("A", "A", None, 6)
tree.create_node("B", "B", "A", 3)
tree.create_node("C", "C", "A", 4)
tree.create_node("D", "D", "A", 5)
tree.create_node("E", "E", "B", 3)
tree.create_node("F", "F", "B", 1)
tree.create_node("G", "G", "C", 6)
tree.create_node("H", "H", "C", 2)
tree.create_node("I", "I", "D", 5)
tree.create_node("J", "J", "D", 4)
tree.create_node("K", "K", "F", 2)
tree.create_node("L", "L", "F", 0)
tree.create_node("M", "M", "F", 4)
tree.create_node("N", "N", "H", 0)
tree.create_node("O", "O", "H", 4)
tree.show()
